// Code generated by sqlc. DO NOT EDIT.

package turnips

import (
	"fmt"
	"time"
)

type AmPm string

const (
	AmPmAm AmPm = "am"
	AmPmPm AmPm = "pm"
)

func (e *AmPm) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AmPm(s)
	case string:
		*e = AmPm(s)
	default:
		return fmt.Errorf("unsupported scan type for AmPm: %T", src)
	}
	return nil
}

type Account struct {
	DiscordID string `json:"discord_id"`
	TimeZone  string `json:"time_zone"`
}

type Nickname struct {
	DiscordID string `json:"discord_id"`
	ServerID  string `json:"server_id"`
	Nickname  string `json:"nickname"`
}

type TurnipPrice struct {
	ID        int64     `json:"id"`
	DiscordID string    `json:"discord_id"`
	Price     int32     `json:"price"`
	AmPm      AmPm      `json:"am_pm"`
	DayOfWeek int32     `json:"day_of_week"`
	DayOfYear int32     `json:"day_of_year"`
	Year      int32     `json:"year"`
	CreatedAt time.Time `json:"created_at"`
	Week      int32     `json:"week"`
}
