// Code generated by sqlc. DO NOT EDIT.

package turnips

import (
	"context"
)

type Querier interface {
	CountAccountsByDiscordId(ctx context.Context, discordID string) (int64, error)
	CountNicknameByDiscordId(ctx context.Context, arg CountNicknameByDiscordIdParams) (int64, error)
	CountPricesByDiscordId(ctx context.Context, discordID string) (int64, error)
	CreateAccount(ctx context.Context, discordID string) (Account, error)
	CreateNickname(ctx context.Context, arg CreateNicknameParams) (Nickname, error)
	CreatePrice(ctx context.Context, arg CreatePriceParams) (TurnipPrice, error)
	DeleteAccount(ctx context.Context, discordID string) error
	DeleteNickname(ctx context.Context, discordID string) error
	DeletePricesForUser(ctx context.Context, discordID string) error
	GetAccount(ctx context.Context, discordID string) (Account, error)
	GetHistoricalWeekPriceHistoryByAccount(ctx context.Context, arg GetHistoricalWeekPriceHistoryByAccountParams) ([]GetHistoricalWeekPriceHistoryByAccountRow, error)
	GetHistoricalWeekPriceHistoryByServer(ctx context.Context, arg GetHistoricalWeekPriceHistoryByServerParams) ([]GetHistoricalWeekPriceHistoryByServerRow, error)
	GetNickname(ctx context.Context, arg GetNicknameParams) (Nickname, error)
	GetWeeksPriceHistoryByAccount(ctx context.Context, arg GetWeeksPriceHistoryByAccountParams) ([]GetWeeksPriceHistoryByAccountRow, error)
	GetWeeksPriceHistoryByServer(ctx context.Context, serverID string) ([]GetWeeksPriceHistoryByServerRow, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListNicknames(ctx context.Context) ([]Nickname, error)
	ListPrices(ctx context.Context) ([]TurnipPrice, error)
	UpdateNickname(ctx context.Context, arg UpdateNicknameParams) (Nickname, error)
	UpdatePrice(ctx context.Context, arg UpdatePriceParams) (TurnipPrice, error)
	UpdateTimeZone(ctx context.Context, arg UpdateTimeZoneParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
