// Code generated by sqlc. DO NOT EDIT.
// source: disable_quips.sql

package wordle

import (
	"context"
)

const checkIfServerHasDisabledQuips = `-- name: CheckIfServerHasDisabledQuips :one
SELECT server_id
from disable_quips
where server_id = $1
`

func (q *Queries) CheckIfServerHasDisabledQuips(ctx context.Context, serverID string) (string, error) {
	row := q.queryRow(ctx, q.checkIfServerHasDisabledQuipsStmt, checkIfServerHasDisabledQuips, serverID)
	var server_id string
	err := row.Scan(&server_id)
	return server_id, err
}

const disableQuipsForServer = `-- name: DisableQuipsForServer :exec
insert into disable_quips (server_id) values ($1)
`

func (q *Queries) DisableQuipsForServer(ctx context.Context, serverID string) error {
	_, err := q.exec(ctx, q.disableQuipsForServerStmt, disableQuipsForServer, serverID)
	return err
}

const enableQuipsForServer = `-- name: EnableQuipsForServer :exec
delete from disable_quips where server_id = $1
`

func (q *Queries) EnableQuipsForServer(ctx context.Context, serverID string) error {
	_, err := q.exec(ctx, q.enableQuipsForServerStmt, enableQuipsForServer, serverID)
	return err
}
