// Code generated by sqlc. DO NOT EDIT.

package wordle

import (
	"context"
)

type Querier interface {
	CountAccountsByDiscordId(ctx context.Context, discordID string) (int64, error)
	CountNicknameByDiscordId(ctx context.Context, arg CountNicknameByDiscordIdParams) (int64, error)
	CountScoresByDiscordId(ctx context.Context, discordID string) (int64, error)
	CreateAccount(ctx context.Context, discordID string) (Account, error)
	CreateNickname(ctx context.Context, arg CreateNicknameParams) (Nickname, error)
	CreateScore(ctx context.Context, arg CreateScoreParams) (WordleScore, error)
	DeleteAccount(ctx context.Context, discordID string) error
	DeleteNickname(ctx context.Context, discordID string) error
	DeleteScoresForUser(ctx context.Context, discordID string) error
	GetAccount(ctx context.Context, discordID string) (Account, error)
	GetNickname(ctx context.Context, arg GetNicknameParams) (Nickname, error)
	GetScoreHistoryByAccount(ctx context.Context, arg GetScoreHistoryByAccountParams) ([]GetScoreHistoryByAccountRow, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListNicknames(ctx context.Context) ([]Nickname, error)
	ListScores(ctx context.Context) ([]WordleScore, error)
	UpdateNickname(ctx context.Context, arg UpdateNicknameParams) (Nickname, error)
	UpdateScore(ctx context.Context, arg UpdateScoreParams) (WordleScore, error)
	UpdateTimeZone(ctx context.Context, arg UpdateTimeZoneParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
