// Code generated by sqlc. DO NOT EDIT.
// source: quips.sql

package wordle

import (
	"context"
	"database/sql"
)

const createQuipForScore = `-- name: CreateQuipForScore :one
insert into quips (score_value, quip, inside_joke, inside_joke_server_id, created_by_account)
VALUES ($1, $2, $3, $4, $5) returning id, score_value, quip, inside_joke, inside_joke_server_id, created_by_account, created_at
`

type CreateQuipForScoreParams struct {
	ScoreValue         int32          `json:"score_value"`
	Quip               string         `json:"quip"`
	InsideJoke         bool           `json:"inside_joke"`
	InsideJokeServerID sql.NullString `json:"inside_joke_server_id"`
	CreatedByAccount   string         `json:"created_by_account"`
}

func (q *Queries) CreateQuipForScore(ctx context.Context, arg CreateQuipForScoreParams) (Quip, error) {
	row := q.queryRow(ctx, q.createQuipForScoreStmt, createQuipForScore,
		arg.ScoreValue,
		arg.Quip,
		arg.InsideJoke,
		arg.InsideJokeServerID,
		arg.CreatedByAccount,
	)
	var i Quip
	err := row.Scan(
		&i.ID,
		&i.ScoreValue,
		&i.Quip,
		&i.InsideJoke,
		&i.InsideJokeServerID,
		&i.CreatedByAccount,
		&i.CreatedAt,
	)
	return i, err
}

const getQuipByScore = `-- name: GetQuipByScore :one
SELECT id, score_value, quip, inside_joke, inside_joke_server_id, created_by_account, created_at
FROM quips
where score_value = $1
  and (not inside_joke or (inside_joke and inside_joke_server_id = $2))
ORDER BY random()
LIMIT 1
`

type GetQuipByScoreParams struct {
	ScoreValue         int32          `json:"score_value"`
	InsideJokeServerID sql.NullString `json:"inside_joke_server_id"`
}

func (q *Queries) GetQuipByScore(ctx context.Context, arg GetQuipByScoreParams) (Quip, error) {
	row := q.queryRow(ctx, q.getQuipByScoreStmt, getQuipByScore, arg.ScoreValue, arg.InsideJokeServerID)
	var i Quip
	err := row.Scan(
		&i.ID,
		&i.ScoreValue,
		&i.Quip,
		&i.InsideJoke,
		&i.InsideJokeServerID,
		&i.CreatedByAccount,
		&i.CreatedAt,
	)
	return i, err
}

const getQuipsByCreatedByAccount = `-- name: GetQuipsByCreatedByAccount :many
SELECT id, score_value, quip, inside_joke, inside_joke_server_id, created_by_account, created_at
FROM quips
where created_by_account = $1
`

func (q *Queries) GetQuipsByCreatedByAccount(ctx context.Context, createdByAccount string) ([]Quip, error) {
	rows, err := q.query(ctx, q.getQuipsByCreatedByAccountStmt, getQuipsByCreatedByAccount, createdByAccount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quip
	for rows.Next() {
		var i Quip
		if err := rows.Scan(
			&i.ID,
			&i.ScoreValue,
			&i.Quip,
			&i.InsideJoke,
			&i.InsideJokeServerID,
			&i.CreatedByAccount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
